import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IslamifyPlus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className=" lg:w-1/5 absolute left-0">
            <Navbar />
          </div>
          <div className="">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
