import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IslamifyPlus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <div className=" lg:w-1/5 absolute left-0 z-10">
            <Navbar />
          </div>
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
